config/routes.rb
Rails.application.routes.draw do

  root :to => "questions#index"

match "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
match "/signout" => "sessions#destroy", :as => :signout, via: [:get, :post]

  resources :questions

  resources :questions do
    resource :answers, only: :create
  end

  resources :questions do
    resource :best_answers, only: :create
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :best_answer

  validates :description,
    presence: true,
    length: { minimum: 50 }
end

app/models/best_answer.rb
class BestAnswer < ActiveRecord::Base
  belongs_to :question
  has_one :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_one :best_answer
  belongs_to :user

  validates :title,
    presence: true,
    length: { minimum: 40 }
  validates :description,
    presence: true,
    length: { minimum: 150 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])

    @answer = Answer.new(answer_params)

    @answer.question = @question

    if @answer.save
      redirect_to "/questions/#{@question.id}"
    else
      render :template => 'questions/show'
    end

  end

  def answer_params
    params.require(:answer).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/best_answers_controller.rb
class BestAnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])

    @best_answer = BestAnswer.new(best_answer_params)

    @best_answer.question = @question

    if @best_answer.save
      redirect_to "/questions/#{@question.id}"
    else
      render :template => 'questions/show'
    end

  end

  def best_answer_params
    params.require(:answer).permit(:question_id, :answer_id)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /questions
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    if @question.save
      redirect_to @question, notice: 'Question successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render action: 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
  render_options = {
    filter_html:     true,
    hard_wrap:       true,
    link_attributes: { rel: 'nofollow' }
  }
  renderer = CustomHtml.new(render_options)

  extensions = {
    autolink:           true,
    fenced_code_blocks: true,
    lax_spacing:        true,
    no_intra_emphasis:  true,
    strikethrough:      true,
    superscript:        true
  }
  Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag 'http://cdnjs.cloudflare.com/ajax/libs/foundation/5.2.3/css/normalize.css' %>
  <%= stylesheet_link_tag 'http://cdnjs.cloudflare.com/ajax/libs/foundation/5.2.3/css/foundation.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-1.11.0.min.js' %>
  <%= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/foundation/5.2.3/js/foundation.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="large-5 columns">
    <h1><%= link_to 'Rescue Mission', questions_path %></h1>
  </div>
  <div class="large-7 columns">
    <ul class="button-group right">
      <li><a href="<%= new_question_path %>" class="button">Ask Question</a></li>
      <li>
      <% if current_user %>
        <span class="button">Logged in as <%= current_user.name %></span>
      <% else %>
        <%= link_to "Sign in with GitHub", "/auth/github", class: "button" %>
      <% end %>
      </li>
      <% if current_user %>
      <li><%= link_to "Sign Out", signout_path, class:"button" %></li>
      <% end %>

    </ul>
  </div>

</div>
<% if flash.any? %>
  <div class="row">
    <div data-alert class="alert-box  info radius large-12 columns">
      <%= flash[:notice] %>
      <a href="#" class="close">&times;</a>
    </div>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<div class="row">
  <div class="small-10 large-centered columns">
    <div class="form-actions">
      <h1 class="subheader">Edit Question</h1>
      <p>(or <%= link_to 'Delete', question_path(@question.id),
                        method: :delete, data: { confirm: 'Are you sure?' } %>)</p>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns">
    <%= form_for :question, url: question_path(@question), method: :patch do |f| %>

      <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area(:description, size: "24x24") %>
        </div>
      </div>

      <div class="form-actions">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <%= link_to 'Back', questions_path, class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3 class="subheader">Questions</h3>
  </div>
</div>

<% @questions.each do |question| %>
<div class="row panel">
  <div class="row">
    <div class="large-7 columns">
      <h4><%= link_to question.title, question %></h4>
    </div>
    <div class="large-3 columns">
      <em><strong>Created:</strong> <%= question.created_at.to_formatted_s(:short) %></em>
    </div>
    <div class="large-2 columns">
      <% if question.user_id == session[:user_id] %>
        <a href="<%= edit_question_path(question) %>" class="button">Edit Question</a>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <p><%= markdown(question.description) %></p>
    </div>
  </div>
</div>
<% end %>

app/views/questions/new.html.erb
<div class="form-actions">
  <h1>Ask Question</h1>
</div>

<%= form_for(@question, html: { class: 'form-horizontal' }) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', questions_path, class: 'btn' %>
  </div>
<% end %>

app/views/questions/show.html.erb
<p id="notice"></p>
<div class="row">
  <div class="large-12 columns">
    <h2 class="subheader">
    <strong>Question:</strong>
    <%= @question.title %>
    </h2>
    <em>Asked by <%= @question.user.name %></em>
    <br\>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <p>
    <strong>Description:</strong>
    <%= markdown(@question.description) %>
    </p>
    <% if @question.user_id == session[:user_id] %>
    <%= link_to 'Edit Question', edit_question_path(@question.id) %> | <%= link_to 'Delete', question_path(@question.id),
    method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h3>Answer Question</h3>
    <%= form_for [@question, @answer] do |f| %>
    <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.text_area :description %><br>
    <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <h2><strong>Answers:</strong></h2>
  </div>
</div>

  <% @question.answers.order(:created_at).each do |answer| %>
  <div class="row">

      <div class="large-12 columns panel">
        <p>
          <%= "#{answer.description}" %>, <em> <%= "#{answer.created_at}" %></em>
        </p>
      </div>

  </div>
  <% end %>

<%= link_to 'Back', questions_path %>
</div>
</div>